services:
  dev:
    build:
      context: .
      args:
        RUST_VERSION: 1.89.0
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: competitive-lib
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /workspace
    environment:
      - CARGO_TARGET_DIR=/workspace/target/docker-target
      - RUST_BACKTRACE=1
      - RUST_MIN_STACK=268435456
      - RUST_LOG=verify=info
    volumes:
      - ./:/workspace
      - ${HOME}/.cache/competitive-library:/home/rustdev/.cache/competitive-library
      - ${HOME}/.cargo/registry:/usr/local/cargo/registry
      - ${HOME}/.cargo/git:/usr/local/cargo/git
    command: ["bash"]
